import { diffWordsWithSpace, Change } from "diff";
import { DiffToken } from "@/features/pipeline/types/pipeline";

/**
 * Computes word-level diff between original draft and reconciled content
 * @param original Initial content generated by Gemini
 * @param modified Reconciled content after DeepSeek critique
 * @returns Array of DiffToken objects matching the UI schema
 */
export function computeDiff(original: string, modified: string): DiffToken[] {
  const changes: Change[] = diffWordsWithSpace(original, modified);

  return changes.map((part) => {
    if (part.added) {
      return {
        type: "insert" as const,
        text: part.value,
      };
    }
    if (part.removed) {
      return {
        type: "delete" as const,
        text: part.value,
      };
    }
    return {
      type: "normal" as const,
      text: part.value,
    };
  });
}
